### ISSUE TITLE
Landing Screen

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile-shell#19]
# Landing Screen
This is the first screen that users will see when they launch the app
User can click on `Sync as Coordinator` OR `Sync as Participant `
<img width="395" alt="Screen Shot 2023-04-05 at 4 41 24 PM" src="https://user-images.githubusercontent.com/78557542/230206673-1c63b1e2-f0a0-454f-b56d-ca549cc02479.png">

# ToDo:

- [ ] Build Screen
- [ ] OnClick  `Sync as Coordinator` will redirect to https://github.com/digidem/mapeo-mobile-shell/issues/21
- [ ] OnClick `Sync as Participant ` will redirect to  https://github.com/digidem/mapeo-mobile-shell/issues/20
- [ ] Cannot multi-select

# Design:
Full flow here  https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=5-6&t=0cfMhaqi5zzdjXLu-0
