### ISSUE TITLE
Language Selector

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile-shell#35]
# Language Selector
User passed the landing screen and now can select a language

# ToDo
- [ ] Use same design as Landing Screen https://github.com/digidem/mapeo-desktop-shell/issues/13
- [ ] OnClick of `English` will redirect to  the path in english
- [ ] OnClick of `Español` will redirect to  the path in spanish
# Design
Full flow here  https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=5-6&t=0cfMhaqi5zzdjXLu-0
